### ISSUE TITLE
findMany & findFirst throws BadState: No element

### ISSUE THREAD

**Issue by jackstefansky** [odroe/prisma-dart#137]
Calling findMany or findFirst throws:

```
Bad state: No element
#0      ListIterable.reduce (dart:_internal/iterable.dart:181:22)
#1      BinaryEngine._rustLogLevel (package:orm/binary_engine.dart:129:51)
#2      BinaryEngine.environment (package:orm/binary_engine.dart:116:59)
#3      BinaryEngine._createProcess (package:orm/binary_engine.dart:177:20)
#4      BinaryEngine.start (package:orm/binary_engine.dart:145:23)
```

Code that fails:

```
final userMatches = await _prismaClient.user.findMany(
      where: UserWhereInput(
        email: StringFilter(equals: email),
        passwordHash: StringFilter(equals: passwordHash),
      ),
    );
```

I think it might be something related to rust log level mapping.

**Comment by jackstefansky** [comment]
Okay, I think #134 might resolve that.

**Comment by jackstefansky** [comment]
@medz 3.0.2 will resolve all of my current problems

**Comment by medz** [comment]
@jackstefansky Ok, I'm releasing version 3.0.2 right now.
