### ISSUE TITLE
Error in 2.2.1

### ISSUE THREAD

**Issue by jacobaraujo7** [odroe/prisma-dart#29]
After dart run orm generate

```
PS D:\Projects\FTeamERP\backend> dart run orm generate
Generate client...                      Could not format because the source could not be parsed:

line 6826, column 43 of .: Unterminated string literal.
     ╷
6826 │ const  String  schema = 'generator client {
     │                                           ^
     ╵
line 6903, column 5 of .: Unterminated string literal.
     ╷
6903 │ \n}';
     │     ^
     ╵
line 6826, column 25 of .: Expected to find ';'.
     ╷
6826 │ const  String  schema = 'generator client {
     │                         ^^^^^^^^^^^^^^^^^^^
     ╵
line 6827, column 1 of .: Expected a method, getter, setter or operator declaration.
     ╷
6827 │ \n  provider = "prisma-client-dart"
     │ ^
     ╵
line 6827, column 16 of .: Expected to find ';'.
     ╷
6827 │ \n  provider = "prisma-client-dart"
     │                ^^^^^^^^^^^^^^^^^^^^
     ╵
line 6828, column 1 of .: Expected a method, getter, setter or operator declaration.
     ╷
6828 │ \n  previewFeatures = ["interactiveTransactions"]
     │ ^
     ╵
line 6828, column 49 of .: Expected to find ';'.
     ╷
6829 │ \n}
     │  ^
     ╵
(276 more errors...)
#0      DartFormatter.formatSource (package:dart_style/src/dart_formatter.dart:144:7)
#1      DartFormatter.format (package:dart_style/src/dart_formatter.dart:72:12)
#2      generator (file:///C:/Users/jacob/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/orm-2.2.1/bin/src/generator/generator.dart:102:38)
#3      GenerateCommand.runGenerator (file:///C:/Users/jacob/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/orm-2.2.1/bin/src/commands/generate_command.dart:150:11)
<asynchronous suspension>
#4      GenerateCommand.run (file:///C:/Users/jacob/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/orm-2.2.1/bin/src/commands/generate_command.dart:111:30)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#6      main (file:///C:/Users/jacob/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/orm-2.2.1/bin/orm.dart:50:5)
<asynchronous suspension>

```

**Comment by medz** [comment]
Maybe further wrapping is needed for the value at https://github.com/odroe/prisma-dart/blob/main/bin/src/generator/client_builder.dart#L27 just creates a variable of type String.

**Comment by jacobaraujo7** [comment]
> @jacobaraujo7 Can you give a minimal schema code? I need to reproduce. Because I can't reproduce it from the example.

I'm testing with the package example.

**Comment by medz** [comment]
> > @jacobaraujo7 Can you give a minimal schema code? I need to reproduce. Because I can't reproduce it from the example.
> 
> I'm testing with the package example. I'm using Windows.

I think I know how to fix this bug. Later, I will checkout new branch fix it and add Windows system tests to CI.
