### ISSUE TITLE
Error running generate

### ISSUE THREAD

**Issue by apaudel96** [odroe/prisma-dart#31]
Hi, I was just trying out this library but having trouble running `dart run orm generate`.
It results in the following error
```
Download binray query engine           23.7s
FormatException: Unexpected character (at character 1)
/home/ankur/Projects/Dart/tasks/.dart_tool/prisma/query-engine: error while...
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1250:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:915:22)
#3      _parseJson (dart:convert-patch/convert_patch.dart:35:10)
#4      JsonDecoder.convert (dart:convert/json.dart:612:36)
#5      JsonCodec.decode (dart:convert/json.dart:216:41)
#6      jsonDecode (dart:convert/json.dart:155:10)
#7      GenerateCommand.run (file:///home/ankur/.pub-cache/hosted/pub.dartlang.org/orm-2.2.2/bin/src/commands/generate_command.dart:62:20)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#9      main (file:///home/ankur/.pub-cache/hosted/pub.dartlang.org/orm-2.2.2/bin/orm.dart:50:5)
<asynchronous suspension>
```
---
I'm using ubuntu 22.04, schema file is
```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider        = "prisma-client-dart"
  previewFeatures = ["interactiveTransactions"]
}

datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

model Task {
  id   String   @id @default(cuid())
  task String
  done Boolean  @default(false)
  due  DateTime @default(dbgenerated("(datetime('now', '+2 days'))")) //sqlite
}

```

**Comment by jacobaraujo7** [comment]
Hello @apaudel96 .
How package version?

**Comment by apaudel96** [comment]
Hi package version is 2.2.2

**Comment by medz** [comment]
copied your schema and it doesn't appear on macOS, maybe I need to install an ubuntu system to test.

**Comment by apaudel96** [comment]
Ok, so I spun up a couple vms, and can confirm that its probably only a problem with ubuntu.
<hr />

XUbuntu 22.04 - Bug (What i currently use)
Stock Ubuntu 22.04 - Bug
Debian 11 - Works as expected
Manjaro - Works as expected

**Comment by medz** [comment]
@apaudel96 
This should be fixed in this PR #32. I created `ubuntu:22.04` in Docker and ran the `example/sqlite` example successfully.

Below is my debug info:
```log
root@0fea44c423ca:/prisma-dart# cd example/sqlite/
root@0fea44c423ca:/prisma-dart/example/sqlite# dart run orm generate
Building package executable... (1.3s)
Built orm:orm.
Generation of "client" succeeded        0.0s

root@0fea44c423ca:/prisma-dart/example/sqlite# dart run
Building package executable...
Built sqlite:sqlite.
{id: cl8e3jsg60000k1qcunwd0v13, task: prisma for dart, done: false, due: 2022-09-25T06:23:13.000Z}
```

@apaudel96 I need to wait for the branch of clone #32 and run it once to further confirm if it is fixed. I am waiting for you, after you confirm that the bug has been fixed we will merge it into the main branch and release a new version to announce the fix.

**Comment by apaudel96** [comment]
@medz Can confirm that #32 works on my computer as well.
Thanks

**Comment by medz** [comment]
> @medz Can confirm that #32 works on my computer as well. Thanks

@apaudel96 Great, I'll merge #32 and release a new version.
